import {StyleSheet} from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F1F5F9',
    },
    keyboardAvoidingView: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 40,
    },
    header: {
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 20,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#075985',
        letterSpacing: -0.5,
    },
    card: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 20,
        borderRadius: 32,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 12},
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 8,
        alignItems: 'center',
    },
    imageContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#EFF6FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        overflow: 'hidden',
    },
    doctorImage: {
        width: 80,
        height: 80,
        resizeMode: 'contain',
    },
    title: {
        fontSize: 24,
        fontWeight: '700',
        color: '#0F172A',
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 14,
        color: '#64748B',
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 32,
        paddingHorizontal: 10,
    },
    form: {
        width: '100%',
    },
    label: {
        fontSize: 12,
        fontWeight: '700',
        color: '#334155',
        marginBottom: 8,
        letterSpacing: 0.5,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8FAFC',
        borderRadius: 16,
        paddingHorizontal: 16,
        height: 60,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#F1F5F9',
    },
    inputIcon: {
        width: 22,
        height: 22,
        marginRight: 12,
        tintColor: '#94A3B8',
        resizeMode: 'contain',
    },
    input: {
        flex: 1,
        color: '#1E293B',
        fontSize: 15,
    },
    optionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 28,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: '#CBD5E1',
        marginRight: 10,
    },
    checkboxActive: {
        backgroundColor: '#0085C7',
        borderColor: '#0085C7',
    },
    optionText: {
        fontSize: 13,
        color: '#475569',
    },
    link: {
        fontSize: 13,
        color: '#0085C7',
        fontWeight: '600',
    },
    loginButton: {
        backgroundColor: '#0070A8',
        height: 60,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#0085C7',
        shadowOffset: {width: 0, height: 6},
        shadowOpacity: 0.25,
        shadowRadius: 12,
        elevation: 6,
    },
    loginButtonDisabled: {
        opacity: 0.6,
    },
    loginButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    complianceBox: {
        flexDirection: 'row',
        backgroundColor: '#F1F5F9',
        borderRadius: 16,
        padding: 16,
        marginTop: 24,
        gap: 12,
    },
    complianceIcon: {
        marginTop: 2,
    },
    complianceText: {
        flex: 1,
        fontSize: 11,
        color: '#475569',
        lineHeight: 16,
    },
    complianceHighlight: {
        fontWeight: '700',
    },
    securityBadges: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 20,
        marginTop: 32,
    },
    badgeItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    badgeText: {
        fontSize: 10,
        fontWeight: '600',
        color: '#94A3B8',
    },
    socialIcons: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 32,
        marginTop: 40,
    },
    iconWrapper: {
        alignItems: 'center',
        gap: 8,
    },
    socialBtn: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    iconLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#64748B',
        letterSpacing: 0.5,
    },
    simpleFooter: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 32,
        gap: 12,
    },
    simpleFooterLink: {
        fontSize: 12,
        color: '#64748B',
    },
    dot: {
        width: 4,
        height: 4,
        borderRadius: 2,
        backgroundColor: '#CBD5E1',
    },
});

export default styles;
