spring.application.name=saude-monitor

# MongoDB / Percona MongoDB
spring.mongodb.uri=mongodb://${MONGO_USER:saude_monitor_user}:${MONGO_PASSWORD:saude_monitor_pass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:saude_monitor}?authSource=${MONGO_AUTH_DB:admin}
spring.data.mongodb.uri=mongodb://${MONGO_USER:saude_monitor_user}:${MONGO_PASSWORD:saude_monitor_pass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:saude_monitor}?authSource=${MONGO_AUTH_DB:admin}
spring.data.mongodb.auto-index-creation=true


